version: "3.9"
services:
  postgres:
    image: postgres:15
    container_name: barter_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: barter_user
      POSTGRES_PASSWORD: barter_password
      POSTGRES_DB: barter_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:


#  DATABASE_URL=postgresql://barter_user:barter_password@localhost:5432/barter_db